obj-$(CONFIG_MXC_IPU_V3) = mxc_ipu.o
# mco-mco
ccflags-$(CONFIG_EDISON_BOARD_RGB) += -DCONFIG_EDISON
mxc_ipu-objs := ipu_common.o ipu_ic.o ipu_disp.o ipu_capture.o ipu_device.o ipu_calc_stripes_sizes.o vdoa.o

